// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

#include <stdarg.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wformat-security"

#include "a2.hpp"

extern "C" void a2__3b6434d4644a0b24() {
	a2();
}

#pragma clang diagnostic pop
