// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

fn refAllDecls(comptime T: type) void {
    inline for (comptime @import("std").meta.declarations(T)) |decl| {
        _ = &@field(T, decl.name);
    }
}

pub const a2 = a2__3b6434d4644a0b24;
extern fn a2__3b6434d4644a0b24() callconv(.c) void;

comptime {
    refAllDecls(@This());
}
