// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

fn refAllDecls(comptime T: type) void {
    inline for (comptime @import("std").meta.declarations(T)) |decl| {
        _ = &@field(T, decl.name);
    }
}

pub const root3 = root3__81839bc52d8cade4;
extern fn root3__81839bc52d8cade4() callconv(.c) void;

comptime {
    refAllDecls(@This());
}
