// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

#include <stdarg.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wformat-security"

#include "root3.hpp"

extern "C" void root3__81839bc52d8cade4() {
	root3();
}

#pragma clang diagnostic pop
