// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

fn refAllDecls(comptime T: type) void {
    inline for (comptime @import("std").meta.declarations(T)) |decl| {
        _ = &@field(T, decl.name);
    }
}

pub const root2 = root2__7bae6d1846503248;
extern fn root2__7bae6d1846503248() callconv(.c) void;

pub const Root2 = extern struct {
    x: i32,
    comptime {
        if (@sizeOf(@This()) != 4 or @alignOf(@This()) != 4) {
            @compileLog(@import("std").fmt.comptimePrint("Expected type 'Root2' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
                @sizeOf(@This()),
                @alignOf(@This()),
            }));

            const this: @This() = undefined;

            const T_x = @TypeOf(this.x);
            if (@sizeOf(T_x) != 4 or @alignOf(T_x) != 4) {
                @compileLog(@import("std").fmt.comptimePrint("Expected field 'x' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
                    @sizeOf(T_x),
                    @alignOf(T_x),
                }));
            }
        }
    }
};

comptime {
    refAllDecls(@This());
}
