// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

#include <stdarg.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wformat-security"

#include "root2.hpp"

extern "C" void root2__7bae6d1846503248() {
	root2();
}

#pragma clang diagnostic pop
