// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

fn refAllDecls(comptime T: type) void {
    inline for (comptime @import("std").meta.declarations(T)) |decl| {
        _ = &@field(T, decl.name);
    }
}

pub const root1 = root1__5064896c62488668;
extern fn root1__5064896c62488668(arg: @"root2.hpp".Root2) callconv(.c) void;

pub const @"root2.hpp" = @import("../../root.zig").root.@"root2.hpp";

comptime {
    refAllDecls(@This());
}
