// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

#include <stdarg.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wformat-security"

#include "root1.hpp"

extern "C" void root1__5064896c62488668(Root2 arg) {
	root1(arg);
}

#pragma clang diagnostic pop
