// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

#include <stdarg.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wformat-security"

#include "tiny_obj_loader.h"

extern "C" const std::vector<float>* tinyobj_attrib_t_GetVertices__ade1ad9d4ee38280(tinyobj::attrib_t* obj) {
	return &obj->GetVertices();
}
extern "C" const std::vector<float>* tinyobj_attrib_t_GetVertexWeights__8a877aac0e30417c(tinyobj::attrib_t* obj) {
	return &obj->GetVertexWeights();
}
extern "C" bool tinyobj_LoadObj__9c97695546c1b63b(tinyobj::attrib_t* attrib, std::vector<tinyobj::shape_t>* shapes, std::vector<tinyobj::material_t>* materials, std::string* warn, std::string* err, const char* filename, const char* mtl_basedir, bool triangulate, bool default_vcols_fallback) {
	return tinyobj::LoadObj(attrib, shapes, materials, warn, err, filename, mtl_basedir, triangulate, default_vcols_fallback);
}
extern "C" bool tinyobj_LoadObjWithCallback__52931123d4e56fb5(std::basic_istream<char>* inStream, const tinyobj::callback_t* callback, void* user_data, tinyobj::MaterialReader* readMatFn, std::string* warn, std::string* err) {
	return tinyobj::LoadObjWithCallback(*inStream, *callback, user_data, readMatFn, warn, err);
}
extern "C" bool tinyobj_LoadObj__9c97695546c1b63b_1(tinyobj::attrib_t* attrib, std::vector<tinyobj::shape_t>* shapes, std::vector<tinyobj::material_t>* materials, std::string* warn, std::string* err, std::basic_istream<char>* inStream, tinyobj::MaterialReader* readMatFn, bool triangulate, bool default_vcols_fallback) {
	return tinyobj::LoadObj(attrib, shapes, materials, warn, err, inStream, readMatFn, triangulate, default_vcols_fallback);
}
extern "C" void tinyobj_LoadMtl__12b0de2f90db3c20(std::map<std::string, int>* material_map, std::vector<tinyobj::material_t>* materials, std::basic_istream<char>* inStream, std::string* warning, std::string* err) {
	tinyobj::LoadMtl(material_map, materials, inStream, warning, err);
}
extern "C" bool tinyobj_ParseTextureNameAndOption__62f137e86a2aae1(std::string* texname, tinyobj::texture_option_t* texopt, const char* linebuf) {
	return tinyobj::ParseTextureNameAndOption(texname, texopt, linebuf);
}

#pragma clang diagnostic pop
