// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

fn refAllDecls(comptime T: type) void {
    inline for (comptime @import("std").meta.declarations(T)) |decl| {
        _ = &@field(T, decl.name);
    }
}

pub const tinyobj = struct {
pub const real_t = f32;

pub const texture_type_t = packed struct(u32) {
data: u32,
pub const TEXTURE_TYPE_NONE: tinyobj.texture_type_t = .{.data=0};
pub const TEXTURE_TYPE_SPHERE: tinyobj.texture_type_t = .{.data=1};
pub const TEXTURE_TYPE_CUBE_TOP: tinyobj.texture_type_t = .{.data=2};
pub const TEXTURE_TYPE_CUBE_BOTTOM: tinyobj.texture_type_t = .{.data=3};
pub const TEXTURE_TYPE_CUBE_FRONT: tinyobj.texture_type_t = .{.data=4};
pub const TEXTURE_TYPE_CUBE_BACK: tinyobj.texture_type_t = .{.data=5};
pub const TEXTURE_TYPE_CUBE_LEFT: tinyobj.texture_type_t = .{.data=6};
pub const TEXTURE_TYPE_CUBE_RIGHT: tinyobj.texture_type_t = .{.data=7};
};

pub const texture_option_t = extern struct {
type: tinyobj.texture_type_t,
sharpness: f32,
brightness: f32,
contrast: f32,
origin_offset: [3]f32,
scale: [3]f32,
turbulence: [3]f32,
texture_resolution: i32,
clamp: bool,
imfchan: u8,
blendu: bool,
blendv: bool,
bump_multiplier: f32,
colorspace: [24]u8 align(8),
comptime {
if (@sizeOf(@This()) != 88 or @alignOf(@This()) != 8) {
@compileLog(@import("std").fmt.comptimePrint("Expected type 'texture_option_t' to be 88 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
    @sizeOf(@This()),
    @alignOf(@This()),
}));

const this: @This() = undefined;

const T_type = @TypeOf(this.type);
if (@sizeOf(T_type) != 4 or @alignOf(T_type) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'type' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_type),
        @alignOf(T_type),
    }));
}
const T_sharpness = @TypeOf(this.sharpness);
if (@sizeOf(T_sharpness) != 4 or @alignOf(T_sharpness) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'sharpness' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_sharpness),
        @alignOf(T_sharpness),
    }));
}
const T_brightness = @TypeOf(this.brightness);
if (@sizeOf(T_brightness) != 4 or @alignOf(T_brightness) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'brightness' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_brightness),
        @alignOf(T_brightness),
    }));
}
const T_contrast = @TypeOf(this.contrast);
if (@sizeOf(T_contrast) != 4 or @alignOf(T_contrast) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'contrast' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_contrast),
        @alignOf(T_contrast),
    }));
}
const T_origin_offset = @TypeOf(this.origin_offset);
if (@sizeOf(T_origin_offset) != 12 or @alignOf(T_origin_offset) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'origin_offset' to be 12 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_origin_offset),
        @alignOf(T_origin_offset),
    }));
}
const T_scale = @TypeOf(this.scale);
if (@sizeOf(T_scale) != 12 or @alignOf(T_scale) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'scale' to be 12 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_scale),
        @alignOf(T_scale),
    }));
}
const T_turbulence = @TypeOf(this.turbulence);
if (@sizeOf(T_turbulence) != 12 or @alignOf(T_turbulence) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'turbulence' to be 12 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_turbulence),
        @alignOf(T_turbulence),
    }));
}
const T_texture_resolution = @TypeOf(this.texture_resolution);
if (@sizeOf(T_texture_resolution) != 4 or @alignOf(T_texture_resolution) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'texture_resolution' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_texture_resolution),
        @alignOf(T_texture_resolution),
    }));
}
const T_clamp = @TypeOf(this.clamp);
if (@sizeOf(T_clamp) != 1 or @alignOf(T_clamp) != 1) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'clamp' to be 1 bytes with 1 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_clamp),
        @alignOf(T_clamp),
    }));
}
const T_imfchan = @TypeOf(this.imfchan);
if (@sizeOf(T_imfchan) != 1 or @alignOf(T_imfchan) != 1) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'imfchan' to be 1 bytes with 1 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_imfchan),
        @alignOf(T_imfchan),
    }));
}
const T_blendu = @TypeOf(this.blendu);
if (@sizeOf(T_blendu) != 1 or @alignOf(T_blendu) != 1) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'blendu' to be 1 bytes with 1 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_blendu),
        @alignOf(T_blendu),
    }));
}
const T_blendv = @TypeOf(this.blendv);
if (@sizeOf(T_blendv) != 1 or @alignOf(T_blendv) != 1) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'blendv' to be 1 bytes with 1 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_blendv),
        @alignOf(T_blendv),
    }));
}
const T_bump_multiplier = @TypeOf(this.bump_multiplier);
if (@sizeOf(T_bump_multiplier) != 4 or @alignOf(T_bump_multiplier) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'bump_multiplier' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_bump_multiplier),
        @alignOf(T_bump_multiplier),
    }));
}
const T_colorspace = @TypeOf(this.colorspace);
if (@sizeOf(T_colorspace) != 24 or @alignOf(T_colorspace) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'colorspace' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_colorspace),
        @alignOf(T_colorspace),
    }));
}
}
}};

pub const material_t = extern struct {
name: [24]u8 align(8),
ambient: [3]f32,
diffuse: [3]f32,
specular: [3]f32,
transmittance: [3]f32,
emission: [3]f32,
shininess: f32,
ior: f32,
dissolve: f32,
illum: i32,
dummy: i32,
ambient_texname: [24]u8 align(8),
diffuse_texname: [24]u8 align(8),
specular_texname: [24]u8 align(8),
specular_highlight_texname: [24]u8 align(8),
bump_texname: [24]u8 align(8),
displacement_texname: [24]u8 align(8),
alpha_texname: [24]u8 align(8),
reflection_texname: [24]u8 align(8),
ambient_texopt: tinyobj.texture_option_t,
diffuse_texopt: tinyobj.texture_option_t,
specular_texopt: tinyobj.texture_option_t,
specular_highlight_texopt: tinyobj.texture_option_t,
bump_texopt: tinyobj.texture_option_t,
displacement_texopt: tinyobj.texture_option_t,
alpha_texopt: tinyobj.texture_option_t,
reflection_texopt: tinyobj.texture_option_t,
roughness: f32,
metallic: f32,
sheen: f32,
clearcoat_thickness: f32,
clearcoat_roughness: f32,
anisotropy: f32,
anisotropy_rotation: f32,
pad0: f32,
roughness_texname: [24]u8 align(8),
metallic_texname: [24]u8 align(8),
sheen_texname: [24]u8 align(8),
emissive_texname: [24]u8 align(8),
normal_texname: [24]u8 align(8),
roughness_texopt: tinyobj.texture_option_t,
metallic_texopt: tinyobj.texture_option_t,
sheen_texopt: tinyobj.texture_option_t,
emissive_texopt: tinyobj.texture_option_t,
normal_texopt: tinyobj.texture_option_t,
pad2: i32,
unknown_parameter: [24]u8 align(8),
comptime {
if (@sizeOf(@This()) != 1624 or @alignOf(@This()) != 8) {
@compileLog(@import("std").fmt.comptimePrint("Expected type 'material_t' to be 1624 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
    @sizeOf(@This()),
    @alignOf(@This()),
}));

const this: @This() = undefined;

const T_name = @TypeOf(this.name);
if (@sizeOf(T_name) != 24 or @alignOf(T_name) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'name' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_name),
        @alignOf(T_name),
    }));
}
const T_ambient = @TypeOf(this.ambient);
if (@sizeOf(T_ambient) != 12 or @alignOf(T_ambient) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'ambient' to be 12 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_ambient),
        @alignOf(T_ambient),
    }));
}
const T_diffuse = @TypeOf(this.diffuse);
if (@sizeOf(T_diffuse) != 12 or @alignOf(T_diffuse) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'diffuse' to be 12 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_diffuse),
        @alignOf(T_diffuse),
    }));
}
const T_specular = @TypeOf(this.specular);
if (@sizeOf(T_specular) != 12 or @alignOf(T_specular) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'specular' to be 12 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_specular),
        @alignOf(T_specular),
    }));
}
const T_transmittance = @TypeOf(this.transmittance);
if (@sizeOf(T_transmittance) != 12 or @alignOf(T_transmittance) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'transmittance' to be 12 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_transmittance),
        @alignOf(T_transmittance),
    }));
}
const T_emission = @TypeOf(this.emission);
if (@sizeOf(T_emission) != 12 or @alignOf(T_emission) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'emission' to be 12 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_emission),
        @alignOf(T_emission),
    }));
}
const T_shininess = @TypeOf(this.shininess);
if (@sizeOf(T_shininess) != 4 or @alignOf(T_shininess) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'shininess' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_shininess),
        @alignOf(T_shininess),
    }));
}
const T_ior = @TypeOf(this.ior);
if (@sizeOf(T_ior) != 4 or @alignOf(T_ior) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'ior' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_ior),
        @alignOf(T_ior),
    }));
}
const T_dissolve = @TypeOf(this.dissolve);
if (@sizeOf(T_dissolve) != 4 or @alignOf(T_dissolve) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'dissolve' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_dissolve),
        @alignOf(T_dissolve),
    }));
}
const T_illum = @TypeOf(this.illum);
if (@sizeOf(T_illum) != 4 or @alignOf(T_illum) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'illum' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_illum),
        @alignOf(T_illum),
    }));
}
const T_dummy = @TypeOf(this.dummy);
if (@sizeOf(T_dummy) != 4 or @alignOf(T_dummy) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'dummy' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_dummy),
        @alignOf(T_dummy),
    }));
}
const T_ambient_texname = @TypeOf(this.ambient_texname);
if (@sizeOf(T_ambient_texname) != 24 or @alignOf(T_ambient_texname) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'ambient_texname' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_ambient_texname),
        @alignOf(T_ambient_texname),
    }));
}
const T_diffuse_texname = @TypeOf(this.diffuse_texname);
if (@sizeOf(T_diffuse_texname) != 24 or @alignOf(T_diffuse_texname) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'diffuse_texname' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_diffuse_texname),
        @alignOf(T_diffuse_texname),
    }));
}
const T_specular_texname = @TypeOf(this.specular_texname);
if (@sizeOf(T_specular_texname) != 24 or @alignOf(T_specular_texname) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'specular_texname' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_specular_texname),
        @alignOf(T_specular_texname),
    }));
}
const T_specular_highlight_texname = @TypeOf(this.specular_highlight_texname);
if (@sizeOf(T_specular_highlight_texname) != 24 or @alignOf(T_specular_highlight_texname) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'specular_highlight_texname' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_specular_highlight_texname),
        @alignOf(T_specular_highlight_texname),
    }));
}
const T_bump_texname = @TypeOf(this.bump_texname);
if (@sizeOf(T_bump_texname) != 24 or @alignOf(T_bump_texname) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'bump_texname' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_bump_texname),
        @alignOf(T_bump_texname),
    }));
}
const T_displacement_texname = @TypeOf(this.displacement_texname);
if (@sizeOf(T_displacement_texname) != 24 or @alignOf(T_displacement_texname) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'displacement_texname' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_displacement_texname),
        @alignOf(T_displacement_texname),
    }));
}
const T_alpha_texname = @TypeOf(this.alpha_texname);
if (@sizeOf(T_alpha_texname) != 24 or @alignOf(T_alpha_texname) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'alpha_texname' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_alpha_texname),
        @alignOf(T_alpha_texname),
    }));
}
const T_reflection_texname = @TypeOf(this.reflection_texname);
if (@sizeOf(T_reflection_texname) != 24 or @alignOf(T_reflection_texname) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'reflection_texname' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_reflection_texname),
        @alignOf(T_reflection_texname),
    }));
}
const T_ambient_texopt = @TypeOf(this.ambient_texopt);
if (@sizeOf(T_ambient_texopt) != 88 or @alignOf(T_ambient_texopt) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'ambient_texopt' to be 88 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_ambient_texopt),
        @alignOf(T_ambient_texopt),
    }));
}
const T_diffuse_texopt = @TypeOf(this.diffuse_texopt);
if (@sizeOf(T_diffuse_texopt) != 88 or @alignOf(T_diffuse_texopt) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'diffuse_texopt' to be 88 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_diffuse_texopt),
        @alignOf(T_diffuse_texopt),
    }));
}
const T_specular_texopt = @TypeOf(this.specular_texopt);
if (@sizeOf(T_specular_texopt) != 88 or @alignOf(T_specular_texopt) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'specular_texopt' to be 88 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_specular_texopt),
        @alignOf(T_specular_texopt),
    }));
}
const T_specular_highlight_texopt = @TypeOf(this.specular_highlight_texopt);
if (@sizeOf(T_specular_highlight_texopt) != 88 or @alignOf(T_specular_highlight_texopt) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'specular_highlight_texopt' to be 88 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_specular_highlight_texopt),
        @alignOf(T_specular_highlight_texopt),
    }));
}
const T_bump_texopt = @TypeOf(this.bump_texopt);
if (@sizeOf(T_bump_texopt) != 88 or @alignOf(T_bump_texopt) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'bump_texopt' to be 88 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_bump_texopt),
        @alignOf(T_bump_texopt),
    }));
}
const T_displacement_texopt = @TypeOf(this.displacement_texopt);
if (@sizeOf(T_displacement_texopt) != 88 or @alignOf(T_displacement_texopt) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'displacement_texopt' to be 88 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_displacement_texopt),
        @alignOf(T_displacement_texopt),
    }));
}
const T_alpha_texopt = @TypeOf(this.alpha_texopt);
if (@sizeOf(T_alpha_texopt) != 88 or @alignOf(T_alpha_texopt) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'alpha_texopt' to be 88 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_alpha_texopt),
        @alignOf(T_alpha_texopt),
    }));
}
const T_reflection_texopt = @TypeOf(this.reflection_texopt);
if (@sizeOf(T_reflection_texopt) != 88 or @alignOf(T_reflection_texopt) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'reflection_texopt' to be 88 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_reflection_texopt),
        @alignOf(T_reflection_texopt),
    }));
}
const T_roughness = @TypeOf(this.roughness);
if (@sizeOf(T_roughness) != 4 or @alignOf(T_roughness) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'roughness' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_roughness),
        @alignOf(T_roughness),
    }));
}
const T_metallic = @TypeOf(this.metallic);
if (@sizeOf(T_metallic) != 4 or @alignOf(T_metallic) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'metallic' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_metallic),
        @alignOf(T_metallic),
    }));
}
const T_sheen = @TypeOf(this.sheen);
if (@sizeOf(T_sheen) != 4 or @alignOf(T_sheen) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'sheen' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_sheen),
        @alignOf(T_sheen),
    }));
}
const T_clearcoat_thickness = @TypeOf(this.clearcoat_thickness);
if (@sizeOf(T_clearcoat_thickness) != 4 or @alignOf(T_clearcoat_thickness) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'clearcoat_thickness' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_clearcoat_thickness),
        @alignOf(T_clearcoat_thickness),
    }));
}
const T_clearcoat_roughness = @TypeOf(this.clearcoat_roughness);
if (@sizeOf(T_clearcoat_roughness) != 4 or @alignOf(T_clearcoat_roughness) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'clearcoat_roughness' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_clearcoat_roughness),
        @alignOf(T_clearcoat_roughness),
    }));
}
const T_anisotropy = @TypeOf(this.anisotropy);
if (@sizeOf(T_anisotropy) != 4 or @alignOf(T_anisotropy) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'anisotropy' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_anisotropy),
        @alignOf(T_anisotropy),
    }));
}
const T_anisotropy_rotation = @TypeOf(this.anisotropy_rotation);
if (@sizeOf(T_anisotropy_rotation) != 4 or @alignOf(T_anisotropy_rotation) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'anisotropy_rotation' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_anisotropy_rotation),
        @alignOf(T_anisotropy_rotation),
    }));
}
const T_pad0 = @TypeOf(this.pad0);
if (@sizeOf(T_pad0) != 4 or @alignOf(T_pad0) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'pad0' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_pad0),
        @alignOf(T_pad0),
    }));
}
const T_roughness_texname = @TypeOf(this.roughness_texname);
if (@sizeOf(T_roughness_texname) != 24 or @alignOf(T_roughness_texname) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'roughness_texname' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_roughness_texname),
        @alignOf(T_roughness_texname),
    }));
}
const T_metallic_texname = @TypeOf(this.metallic_texname);
if (@sizeOf(T_metallic_texname) != 24 or @alignOf(T_metallic_texname) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'metallic_texname' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_metallic_texname),
        @alignOf(T_metallic_texname),
    }));
}
const T_sheen_texname = @TypeOf(this.sheen_texname);
if (@sizeOf(T_sheen_texname) != 24 or @alignOf(T_sheen_texname) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'sheen_texname' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_sheen_texname),
        @alignOf(T_sheen_texname),
    }));
}
const T_emissive_texname = @TypeOf(this.emissive_texname);
if (@sizeOf(T_emissive_texname) != 24 or @alignOf(T_emissive_texname) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'emissive_texname' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_emissive_texname),
        @alignOf(T_emissive_texname),
    }));
}
const T_normal_texname = @TypeOf(this.normal_texname);
if (@sizeOf(T_normal_texname) != 24 or @alignOf(T_normal_texname) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'normal_texname' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_normal_texname),
        @alignOf(T_normal_texname),
    }));
}
const T_roughness_texopt = @TypeOf(this.roughness_texopt);
if (@sizeOf(T_roughness_texopt) != 88 or @alignOf(T_roughness_texopt) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'roughness_texopt' to be 88 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_roughness_texopt),
        @alignOf(T_roughness_texopt),
    }));
}
const T_metallic_texopt = @TypeOf(this.metallic_texopt);
if (@sizeOf(T_metallic_texopt) != 88 or @alignOf(T_metallic_texopt) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'metallic_texopt' to be 88 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_metallic_texopt),
        @alignOf(T_metallic_texopt),
    }));
}
const T_sheen_texopt = @TypeOf(this.sheen_texopt);
if (@sizeOf(T_sheen_texopt) != 88 or @alignOf(T_sheen_texopt) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'sheen_texopt' to be 88 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_sheen_texopt),
        @alignOf(T_sheen_texopt),
    }));
}
const T_emissive_texopt = @TypeOf(this.emissive_texopt);
if (@sizeOf(T_emissive_texopt) != 88 or @alignOf(T_emissive_texopt) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'emissive_texopt' to be 88 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_emissive_texopt),
        @alignOf(T_emissive_texopt),
    }));
}
const T_normal_texopt = @TypeOf(this.normal_texopt);
if (@sizeOf(T_normal_texopt) != 88 or @alignOf(T_normal_texopt) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'normal_texopt' to be 88 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_normal_texopt),
        @alignOf(T_normal_texopt),
    }));
}
const T_pad2 = @TypeOf(this.pad2);
if (@sizeOf(T_pad2) != 4 or @alignOf(T_pad2) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'pad2' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_pad2),
        @alignOf(T_pad2),
    }));
}
const T_unknown_parameter = @TypeOf(this.unknown_parameter);
if (@sizeOf(T_unknown_parameter) != 24 or @alignOf(T_unknown_parameter) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'unknown_parameter' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_unknown_parameter),
        @alignOf(T_unknown_parameter),
    }));
}
}
}};

pub const tag_t = extern struct {
name: [24]u8 align(8),
intValues: [24]u8 align(8),
floatValues: [24]u8 align(8),
stringValues: [24]u8 align(8),
comptime {
if (@sizeOf(@This()) != 96 or @alignOf(@This()) != 8) {
@compileLog(@import("std").fmt.comptimePrint("Expected type 'tag_t' to be 96 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
    @sizeOf(@This()),
    @alignOf(@This()),
}));

const this: @This() = undefined;

const T_name = @TypeOf(this.name);
if (@sizeOf(T_name) != 24 or @alignOf(T_name) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'name' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_name),
        @alignOf(T_name),
    }));
}
const T_intValues = @TypeOf(this.intValues);
if (@sizeOf(T_intValues) != 24 or @alignOf(T_intValues) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'intValues' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_intValues),
        @alignOf(T_intValues),
    }));
}
const T_floatValues = @TypeOf(this.floatValues);
if (@sizeOf(T_floatValues) != 24 or @alignOf(T_floatValues) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'floatValues' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_floatValues),
        @alignOf(T_floatValues),
    }));
}
const T_stringValues = @TypeOf(this.stringValues);
if (@sizeOf(T_stringValues) != 24 or @alignOf(T_stringValues) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'stringValues' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_stringValues),
        @alignOf(T_stringValues),
    }));
}
}
}};

pub const joint_and_weight_t = extern struct {
joint_id: i32,
weight: f32,
comptime {
if (@sizeOf(@This()) != 8 or @alignOf(@This()) != 4) {
@compileLog(@import("std").fmt.comptimePrint("Expected type 'joint_and_weight_t' to be 8 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
    @sizeOf(@This()),
    @alignOf(@This()),
}));

const this: @This() = undefined;

const T_joint_id = @TypeOf(this.joint_id);
if (@sizeOf(T_joint_id) != 4 or @alignOf(T_joint_id) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'joint_id' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_joint_id),
        @alignOf(T_joint_id),
    }));
}
const T_weight = @TypeOf(this.weight);
if (@sizeOf(T_weight) != 4 or @alignOf(T_weight) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'weight' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_weight),
        @alignOf(T_weight),
    }));
}
}
}};

pub const skin_weight_t = extern struct {
vertex_id: i32,
weightValues: [24]u8 align(8),
comptime {
if (@sizeOf(@This()) != 32 or @alignOf(@This()) != 8) {
@compileLog(@import("std").fmt.comptimePrint("Expected type 'skin_weight_t' to be 32 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
    @sizeOf(@This()),
    @alignOf(@This()),
}));

const this: @This() = undefined;

const T_vertex_id = @TypeOf(this.vertex_id);
if (@sizeOf(T_vertex_id) != 4 or @alignOf(T_vertex_id) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'vertex_id' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_vertex_id),
        @alignOf(T_vertex_id),
    }));
}
const T_weightValues = @TypeOf(this.weightValues);
if (@sizeOf(T_weightValues) != 24 or @alignOf(T_weightValues) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'weightValues' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_weightValues),
        @alignOf(T_weightValues),
    }));
}
}
}};

pub const index_t = extern struct {
vertex_index: i32,
normal_index: i32,
texcoord_index: i32,
comptime {
if (@sizeOf(@This()) != 12 or @alignOf(@This()) != 4) {
@compileLog(@import("std").fmt.comptimePrint("Expected type 'index_t' to be 12 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
    @sizeOf(@This()),
    @alignOf(@This()),
}));

const this: @This() = undefined;

const T_vertex_index = @TypeOf(this.vertex_index);
if (@sizeOf(T_vertex_index) != 4 or @alignOf(T_vertex_index) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'vertex_index' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_vertex_index),
        @alignOf(T_vertex_index),
    }));
}
const T_normal_index = @TypeOf(this.normal_index);
if (@sizeOf(T_normal_index) != 4 or @alignOf(T_normal_index) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'normal_index' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_normal_index),
        @alignOf(T_normal_index),
    }));
}
const T_texcoord_index = @TypeOf(this.texcoord_index);
if (@sizeOf(T_texcoord_index) != 4 or @alignOf(T_texcoord_index) != 4) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'texcoord_index' to be 4 bytes with 4 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_texcoord_index),
        @alignOf(T_texcoord_index),
    }));
}
}
}};

pub const mesh_t = extern struct {
indices: [24]u8 align(8),
num_face_vertices: [24]u8 align(8),
material_ids: [24]u8 align(8),
smoothing_group_ids: [24]u8 align(8),
tags: [24]u8 align(8),
comptime {
if (@sizeOf(@This()) != 120 or @alignOf(@This()) != 8) {
@compileLog(@import("std").fmt.comptimePrint("Expected type 'mesh_t' to be 120 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
    @sizeOf(@This()),
    @alignOf(@This()),
}));

const this: @This() = undefined;

const T_indices = @TypeOf(this.indices);
if (@sizeOf(T_indices) != 24 or @alignOf(T_indices) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'indices' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_indices),
        @alignOf(T_indices),
    }));
}
const T_num_face_vertices = @TypeOf(this.num_face_vertices);
if (@sizeOf(T_num_face_vertices) != 24 or @alignOf(T_num_face_vertices) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'num_face_vertices' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_num_face_vertices),
        @alignOf(T_num_face_vertices),
    }));
}
const T_material_ids = @TypeOf(this.material_ids);
if (@sizeOf(T_material_ids) != 24 or @alignOf(T_material_ids) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'material_ids' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_material_ids),
        @alignOf(T_material_ids),
    }));
}
const T_smoothing_group_ids = @TypeOf(this.smoothing_group_ids);
if (@sizeOf(T_smoothing_group_ids) != 24 or @alignOf(T_smoothing_group_ids) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'smoothing_group_ids' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_smoothing_group_ids),
        @alignOf(T_smoothing_group_ids),
    }));
}
const T_tags = @TypeOf(this.tags);
if (@sizeOf(T_tags) != 24 or @alignOf(T_tags) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'tags' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_tags),
        @alignOf(T_tags),
    }));
}
}
}};

pub const lines_t = extern struct {
indices: [24]u8 align(8),
num_line_vertices: [24]u8 align(8),
comptime {
if (@sizeOf(@This()) != 48 or @alignOf(@This()) != 8) {
@compileLog(@import("std").fmt.comptimePrint("Expected type 'lines_t' to be 48 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
    @sizeOf(@This()),
    @alignOf(@This()),
}));

const this: @This() = undefined;

const T_indices = @TypeOf(this.indices);
if (@sizeOf(T_indices) != 24 or @alignOf(T_indices) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'indices' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_indices),
        @alignOf(T_indices),
    }));
}
const T_num_line_vertices = @TypeOf(this.num_line_vertices);
if (@sizeOf(T_num_line_vertices) != 24 or @alignOf(T_num_line_vertices) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'num_line_vertices' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_num_line_vertices),
        @alignOf(T_num_line_vertices),
    }));
}
}
}};

pub const points_t = extern struct {
indices: [24]u8 align(8),
comptime {
if (@sizeOf(@This()) != 24 or @alignOf(@This()) != 8) {
@compileLog(@import("std").fmt.comptimePrint("Expected type 'points_t' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
    @sizeOf(@This()),
    @alignOf(@This()),
}));

const this: @This() = undefined;

const T_indices = @TypeOf(this.indices);
if (@sizeOf(T_indices) != 24 or @alignOf(T_indices) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'indices' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_indices),
        @alignOf(T_indices),
    }));
}
}
}};

pub const shape_t = extern struct {
name: [24]u8 align(8),
mesh: tinyobj.mesh_t,
lines: tinyobj.lines_t,
points: tinyobj.points_t,
comptime {
if (@sizeOf(@This()) != 216 or @alignOf(@This()) != 8) {
@compileLog(@import("std").fmt.comptimePrint("Expected type 'shape_t' to be 216 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
    @sizeOf(@This()),
    @alignOf(@This()),
}));

const this: @This() = undefined;

const T_name = @TypeOf(this.name);
if (@sizeOf(T_name) != 24 or @alignOf(T_name) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'name' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_name),
        @alignOf(T_name),
    }));
}
const T_mesh = @TypeOf(this.mesh);
if (@sizeOf(T_mesh) != 120 or @alignOf(T_mesh) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'mesh' to be 120 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_mesh),
        @alignOf(T_mesh),
    }));
}
const T_lines = @TypeOf(this.lines);
if (@sizeOf(T_lines) != 48 or @alignOf(T_lines) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'lines' to be 48 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_lines),
        @alignOf(T_lines),
    }));
}
const T_points = @TypeOf(this.points);
if (@sizeOf(T_points) != 24 or @alignOf(T_points) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'points' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_points),
        @alignOf(T_points),
    }));
}
}
}};

pub const attrib_t = extern struct {
vertices: [24]u8 align(8),
vertex_weights: [24]u8 align(8),
normals: [24]u8 align(8),
texcoords: [24]u8 align(8),
texcoord_ws: [24]u8 align(8),
colors: [24]u8 align(8),
skin_weights: [24]u8 align(8),
pub const GetVertices = tinyobj_attrib_t_GetVertices__ade1ad9d4ee38280;
extern fn tinyobj_attrib_t_GetVertices__ade1ad9d4ee38280(self: *@This()) callconv(.c) *const [24]u8;

pub const GetVertexWeights = tinyobj_attrib_t_GetVertexWeights__8a877aac0e30417c;
extern fn tinyobj_attrib_t_GetVertexWeights__8a877aac0e30417c() callconv(.c) *const [24]u8;

comptime {
if (@sizeOf(@This()) != 168 or @alignOf(@This()) != 8) {
@compileLog(@import("std").fmt.comptimePrint("Expected type 'attrib_t' to be 168 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
    @sizeOf(@This()),
    @alignOf(@This()),
}));

const this: @This() = undefined;

const T_vertices = @TypeOf(this.vertices);
if (@sizeOf(T_vertices) != 24 or @alignOf(T_vertices) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'vertices' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_vertices),
        @alignOf(T_vertices),
    }));
}
const T_vertex_weights = @TypeOf(this.vertex_weights);
if (@sizeOf(T_vertex_weights) != 24 or @alignOf(T_vertex_weights) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'vertex_weights' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_vertex_weights),
        @alignOf(T_vertex_weights),
    }));
}
const T_normals = @TypeOf(this.normals);
if (@sizeOf(T_normals) != 24 or @alignOf(T_normals) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'normals' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_normals),
        @alignOf(T_normals),
    }));
}
const T_texcoords = @TypeOf(this.texcoords);
if (@sizeOf(T_texcoords) != 24 or @alignOf(T_texcoords) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'texcoords' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_texcoords),
        @alignOf(T_texcoords),
    }));
}
const T_texcoord_ws = @TypeOf(this.texcoord_ws);
if (@sizeOf(T_texcoord_ws) != 24 or @alignOf(T_texcoord_ws) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'texcoord_ws' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_texcoord_ws),
        @alignOf(T_texcoord_ws),
    }));
}
const T_colors = @TypeOf(this.colors);
if (@sizeOf(T_colors) != 24 or @alignOf(T_colors) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'colors' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_colors),
        @alignOf(T_colors),
    }));
}
const T_skin_weights = @TypeOf(this.skin_weights);
if (@sizeOf(T_skin_weights) != 24 or @alignOf(T_skin_weights) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'skin_weights' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_skin_weights),
        @alignOf(T_skin_weights),
    }));
}
}
}};

pub const callback_t = extern struct {
vertex_cb: [*c]*const fn (*void, f32, f32, f32, f32) callconv(.c) void,
vertex_color_cb: [*c]*const fn (*void, f32, f32, f32, f32, f32, f32, bool) callconv(.c) void,
normal_cb: [*c]*const fn (*void, f32, f32, f32) callconv(.c) void,
texcoord_cb: [*c]*const fn (*void, f32, f32, f32) callconv(.c) void,
index_cb: [*c]*const fn (*void, [*c]tinyobj.index_t, i32) callconv(.c) void,
usemtl_cb: [*c]*const fn (*void, [*c]const u8, i32) callconv(.c) void,
mtllib_cb: [*c]*const fn (*void, [*c]const tinyobj.material_t, i32) callconv(.c) void,
group_cb: [*c]*const fn (*void, [*c][*c]const u8, i32) callconv(.c) void,
object_cb: [*c]*const fn (*void, [*c]const u8) callconv(.c) void,
comptime {
if (@sizeOf(@This()) != 72 or @alignOf(@This()) != 8) {
@compileLog(@import("std").fmt.comptimePrint("Expected type 'callback_t' to be 72 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
    @sizeOf(@This()),
    @alignOf(@This()),
}));

const this: @This() = undefined;

const T_vertex_cb = @TypeOf(this.vertex_cb);
if (@sizeOf(T_vertex_cb) != 8 or @alignOf(T_vertex_cb) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'vertex_cb' to be 8 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_vertex_cb),
        @alignOf(T_vertex_cb),
    }));
}
const T_vertex_color_cb = @TypeOf(this.vertex_color_cb);
if (@sizeOf(T_vertex_color_cb) != 8 or @alignOf(T_vertex_color_cb) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'vertex_color_cb' to be 8 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_vertex_color_cb),
        @alignOf(T_vertex_color_cb),
    }));
}
const T_normal_cb = @TypeOf(this.normal_cb);
if (@sizeOf(T_normal_cb) != 8 or @alignOf(T_normal_cb) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'normal_cb' to be 8 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_normal_cb),
        @alignOf(T_normal_cb),
    }));
}
const T_texcoord_cb = @TypeOf(this.texcoord_cb);
if (@sizeOf(T_texcoord_cb) != 8 or @alignOf(T_texcoord_cb) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'texcoord_cb' to be 8 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_texcoord_cb),
        @alignOf(T_texcoord_cb),
    }));
}
const T_index_cb = @TypeOf(this.index_cb);
if (@sizeOf(T_index_cb) != 8 or @alignOf(T_index_cb) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'index_cb' to be 8 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_index_cb),
        @alignOf(T_index_cb),
    }));
}
const T_usemtl_cb = @TypeOf(this.usemtl_cb);
if (@sizeOf(T_usemtl_cb) != 8 or @alignOf(T_usemtl_cb) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'usemtl_cb' to be 8 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_usemtl_cb),
        @alignOf(T_usemtl_cb),
    }));
}
const T_mtllib_cb = @TypeOf(this.mtllib_cb);
if (@sizeOf(T_mtllib_cb) != 8 or @alignOf(T_mtllib_cb) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'mtllib_cb' to be 8 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_mtllib_cb),
        @alignOf(T_mtllib_cb),
    }));
}
const T_group_cb = @TypeOf(this.group_cb);
if (@sizeOf(T_group_cb) != 8 or @alignOf(T_group_cb) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'group_cb' to be 8 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_group_cb),
        @alignOf(T_group_cb),
    }));
}
const T_object_cb = @TypeOf(this.object_cb);
if (@sizeOf(T_object_cb) != 8 or @alignOf(T_object_cb) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'object_cb' to be 8 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_object_cb),
        @alignOf(T_object_cb),
    }));
}
}
}};

pub const ObjReaderConfig = extern struct {
triangulate: bool,
triangulation_method: [24]u8 align(8),
vertex_color: bool,
mtl_search_path: [24]u8 align(8),
comptime {
if (@sizeOf(@This()) != 64 or @alignOf(@This()) != 8) {
@compileLog(@import("std").fmt.comptimePrint("Expected type 'ObjReaderConfig' to be 64 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
    @sizeOf(@This()),
    @alignOf(@This()),
}));

const this: @This() = undefined;

const T_triangulate = @TypeOf(this.triangulate);
if (@sizeOf(T_triangulate) != 1 or @alignOf(T_triangulate) != 1) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'triangulate' to be 1 bytes with 1 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_triangulate),
        @alignOf(T_triangulate),
    }));
}
const T_triangulation_method = @TypeOf(this.triangulation_method);
if (@sizeOf(T_triangulation_method) != 24 or @alignOf(T_triangulation_method) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'triangulation_method' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_triangulation_method),
        @alignOf(T_triangulation_method),
    }));
}
const T_vertex_color = @TypeOf(this.vertex_color);
if (@sizeOf(T_vertex_color) != 1 or @alignOf(T_vertex_color) != 1) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'vertex_color' to be 1 bytes with 1 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_vertex_color),
        @alignOf(T_vertex_color),
    }));
}
const T_mtl_search_path = @TypeOf(this.mtl_search_path);
if (@sizeOf(T_mtl_search_path) != 24 or @alignOf(T_mtl_search_path) != 8) {
    @compileLog(@import("std").fmt.comptimePrint("Expected field 'mtl_search_path' to be 24 bytes with 8 byte alignment, but was {} bytes with {} byte alignment instead!", .{
        @sizeOf(T_mtl_search_path),
        @alignOf(T_mtl_search_path),
    }));
}
}
}};

pub const LoadObj = tinyobj_LoadObj__9c97695546c1b63b;
extern fn tinyobj_LoadObj__9c97695546c1b63b(attrib: [*c]tinyobj.attrib_t, shapes: [*c][24]u8, materials: [*c][24]u8, warn: [*c][24]u8, err: [*c][24]u8, filename: [*c]const u8, mtl_basedir: [*c]const u8, triangulate: bool, default_vcols_fallback: bool) callconv(.c) bool;

pub const LoadObjWithCallback = tinyobj_LoadObjWithCallback__52931123d4e56fb5;
extern fn tinyobj_LoadObjWithCallback__52931123d4e56fb5(inStream: *?*anyopaque, callback: *const tinyobj.callback_t, user_data: *void, readMatFn: [*c]tinyobj.MaterialReader, warn: [*c][24]u8, err: [*c][24]u8) callconv(.c) bool;

pub const LoadObj_1 = tinyobj_LoadObj__9c97695546c1b63b_1;
extern fn tinyobj_LoadObj__9c97695546c1b63b_1(attrib: [*c]tinyobj.attrib_t, shapes: [*c][24]u8, materials: [*c][24]u8, warn: [*c][24]u8, err: [*c][24]u8, inStream: [*c]?*anyopaque, readMatFn: [*c]tinyobj.MaterialReader, triangulate: bool, default_vcols_fallback: bool) callconv(.c) bool;

pub const LoadMtl = tinyobj_LoadMtl__12b0de2f90db3c20;
extern fn tinyobj_LoadMtl__12b0de2f90db3c20(material_map: [*c]?*anyopaque, materials: [*c][24]u8, inStream: [*c]?*anyopaque, warning: [*c][24]u8, err: [*c][24]u8) callconv(.c) void;

pub const ParseTextureNameAndOption = tinyobj_ParseTextureNameAndOption__62f137e86a2aae1;
extern fn tinyobj_ParseTextureNameAndOption__62f137e86a2aae1(texname: [*c][24]u8, texopt: [*c]tinyobj.texture_option_t, linebuf: [*c]const u8) callconv(.c) bool;



comptime {
    refAllDecls(@This());
}
};

pub const @"vector.h" = @import("tinyobjloader#vector.h")
pub const @"istream.h" = @import("tinyobjloader#istream.h")
pub const @"string" = @import("tinyobjloader#string")
pub const @"map" = @import("tinyobjloader#map")


comptime {
    refAllDecls(@This());
}
