// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

fn refAllDecls(comptime T: type) void {
    inline for (comptime @import("std").meta.declarations(T)) |decl| {
        _ = &@field(T, decl.name);
    }
}

pub const f = f__faff92fe25589f8c;
extern fn f__faff92fe25589f8c(p1: i32, p2: u8) callconv(.c) void;

comptime {
    refAllDecls(@This());
}
