// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

#include <stdarg.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wformat-security"

#include "b3.hpp"

extern "C" void b3__4df39c2c2a900384() {
	b3();
}

#pragma clang diagnostic pop
