// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

fn refAllDecls(comptime T: type) void {
    inline for (comptime @import("std").meta.declarations(T)) |decl| {
        _ = &@field(T, decl.name);
    }
}

pub const b3 = b3__4df39c2c2a900384;
extern fn b3__4df39c2c2a900384() callconv(.c) void;

comptime {
    refAllDecls(@This());
}
