// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

#include <stdarg.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wformat-security"

#include "b1.hpp"

extern "C" void b1__408236ce1bec3329() {
	b1();
}

#pragma clang diagnostic pop
