// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

fn refAllDecls(comptime T: type) void {
    inline for (comptime @import("std").meta.declarations(T)) |decl| {
        _ = &@field(T, decl.name);
    }
}

pub const b1 = b1__408236ce1bec3329;
extern fn b1__408236ce1bec3329() callconv(.c) void;

comptime {
    refAllDecls(@This());
}
