// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

fn refAllDecls(comptime T: type) void {
    inline for (comptime @import("std").meta.declarations(T)) |decl| {
        _ = &@field(T, decl.name);
    }
}

pub const ImGui_ImplSDL3_InitForOpenGL = ImGui_ImplSDL3_InitForOpenGL__e99e10970d5cd092;
extern fn ImGui_ImplSDL3_InitForOpenGL__e99e10970d5cd092(window: [*c]SDL_Window, sdl_gl_context: *void) callconv(.c) bool;

pub const ImGui_ImplSDL3_InitForVulkan = ImGui_ImplSDL3_InitForVulkan__f6f607e2e54fad4;
extern fn ImGui_ImplSDL3_InitForVulkan__f6f607e2e54fad4(window: [*c]SDL_Window) callconv(.c) bool;

pub const ImGui_ImplSDL3_InitForD3D = ImGui_ImplSDL3_InitForD3D__171ea32c74c97ab6;
extern fn ImGui_ImplSDL3_InitForD3D__171ea32c74c97ab6(window: [*c]SDL_Window) callconv(.c) bool;

pub const ImGui_ImplSDL3_InitForMetal = ImGui_ImplSDL3_InitForMetal__766cb8e4cdd4302d;
extern fn ImGui_ImplSDL3_InitForMetal__766cb8e4cdd4302d(window: [*c]SDL_Window) callconv(.c) bool;

pub const ImGui_ImplSDL3_InitForSDLRenderer = ImGui_ImplSDL3_InitForSDLRenderer__9b020ae04454e2d4;
extern fn ImGui_ImplSDL3_InitForSDLRenderer__9b020ae04454e2d4(window: [*c]SDL_Window, renderer: [*c]SDL_Renderer) callconv(.c) bool;

pub const ImGui_ImplSDL3_InitForSDLGPU = ImGui_ImplSDL3_InitForSDLGPU__6a38996488306ede;
extern fn ImGui_ImplSDL3_InitForSDLGPU__6a38996488306ede(window: [*c]SDL_Window) callconv(.c) bool;

pub const ImGui_ImplSDL3_InitForOther = ImGui_ImplSDL3_InitForOther__8558682120ecae20;
extern fn ImGui_ImplSDL3_InitForOther__8558682120ecae20(window: [*c]SDL_Window) callconv(.c) bool;

pub const ImGui_ImplSDL3_Shutdown = ImGui_ImplSDL3_Shutdown__2014beadd6c0478c;
extern fn ImGui_ImplSDL3_Shutdown__2014beadd6c0478c() callconv(.c) void;

pub const ImGui_ImplSDL3_NewFrame = ImGui_ImplSDL3_NewFrame__37c6d7cd43a25335;
extern fn ImGui_ImplSDL3_NewFrame__37c6d7cd43a25335() callconv(.c) void;

pub const ImGui_ImplSDL3_ProcessEvent = ImGui_ImplSDL3_ProcessEvent__decfc6687eb97b8e;
extern fn ImGui_ImplSDL3_ProcessEvent__decfc6687eb97b8e(event: [*c]const SDL_Event) callconv(.c) bool;

pub const ImGui_ImplSDL3_GamepadMode = packed struct(i32) {
    data: i32,
    pub const ImGui_ImplSDL3_GamepadMode_AutoFirst: ImGui_ImplSDL3_GamepadMode = .{ .data = 0 };
    pub const ImGui_ImplSDL3_GamepadMode_AutoAll: ImGui_ImplSDL3_GamepadMode = .{ .data = 1 };
    pub const ImGui_ImplSDL3_GamepadMode_Manual: ImGui_ImplSDL3_GamepadMode = .{ .data = 2 };
};

pub const ImGui_ImplSDL3_SetGamepadMode = ImGui_ImplSDL3_SetGamepadMode__188716f97529355a;
extern fn ImGui_ImplSDL3_SetGamepadMode__188716f97529355a(mode: ImGui_ImplSDL3_GamepadMode, manual_gamepads_array: [*c][*c]SDL_Gamepad, manual_gamepads_count: i32) callconv(.c) void;

pub const SDL_Renderer = ?*anyopaque;
pub const SDL_Window = ?*anyopaque;
pub const SDL_Gamepad = ?*anyopaque;
pub const SDL_Event = ?*anyopaque; // NOTE: Patched

comptime {
    refAllDecls(@This());
}
