// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

#include <stdarg.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wformat-security"

#include "imgui_impl_sdl3.h"

extern "C" bool ImGui_ImplSDL3_InitForOpenGL__e99e10970d5cd092(SDL_Window* window, void* sdl_gl_context) {
	return ImGui_ImplSDL3_InitForOpenGL(window, sdl_gl_context);
}
extern "C" bool ImGui_ImplSDL3_InitForVulkan__f6f607e2e54fad4(SDL_Window* window) {
	return ImGui_ImplSDL3_InitForVulkan(window);
}
extern "C" bool ImGui_ImplSDL3_InitForD3D__171ea32c74c97ab6(SDL_Window* window) {
	return ImGui_ImplSDL3_InitForD3D(window);
}
extern "C" bool ImGui_ImplSDL3_InitForMetal__766cb8e4cdd4302d(SDL_Window* window) {
	return ImGui_ImplSDL3_InitForMetal(window);
}
extern "C" bool ImGui_ImplSDL3_InitForSDLRenderer__9b020ae04454e2d4(SDL_Window* window, SDL_Renderer* renderer) {
	return ImGui_ImplSDL3_InitForSDLRenderer(window, renderer);
}
extern "C" bool ImGui_ImplSDL3_InitForSDLGPU__6a38996488306ede(SDL_Window* window) {
	return ImGui_ImplSDL3_InitForSDLGPU(window);
}
extern "C" bool ImGui_ImplSDL3_InitForOther__8558682120ecae20(SDL_Window* window) {
	return ImGui_ImplSDL3_InitForOther(window);
}
extern "C" void ImGui_ImplSDL3_Shutdown__2014beadd6c0478c() {
	ImGui_ImplSDL3_Shutdown();
}
extern "C" void ImGui_ImplSDL3_NewFrame__37c6d7cd43a25335() {
	ImGui_ImplSDL3_NewFrame();
}
extern "C" bool ImGui_ImplSDL3_ProcessEvent__decfc6687eb97b8e(const const SDL_Event* event) {
	return ImGui_ImplSDL3_ProcessEvent(event);
}
extern "C" void ImGui_ImplSDL3_SetGamepadMode__188716f97529355a(ImGui_ImplSDL3_GamepadMode mode, SDL_Gamepad** manual_gamepads_array, int manual_gamepads_count) {
	ImGui_ImplSDL3_SetGamepadMode(mode, manual_gamepads_array, manual_gamepads_count);
}
#pragma clang diagnostic pop