// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

#include <stdarg.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wformat-security"

#include "c3.hpp"

extern "C" void c3__63e63ded62496865() {
	c3();
}

#pragma clang diagnostic pop
