// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

#include <stdarg.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wformat-security"


extern "C" void f__faff92fe25589f8c(int p1, char p2) {
	f(p1, p2);
}

#pragma clang diagnostic pop