// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

#include <stdarg.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wformat-security"

#include "imgui_impl_sdlgpu3.h"

extern "C" bool ImGui_ImplSDLGPU3_Init__600d26a5acf96a01(ImGui_ImplSDLGPU3_InitInfo* info) {
	return ImGui_ImplSDLGPU3_Init(info);
}
extern "C" void ImGui_ImplSDLGPU3_Shutdown__13b42b5729a15b3() {
	ImGui_ImplSDLGPU3_Shutdown();
}
extern "C" void ImGui_ImplSDLGPU3_NewFrame__65431eefe517df84() {
	ImGui_ImplSDLGPU3_NewFrame();
}
extern "C" void ImGui_ImplSDLGPU3_PrepareDrawData__93ec289e13d03601(ImDrawData* draw_data, SDL_GPUCommandBuffer* command_buffer) {
	ImGui_ImplSDLGPU3_PrepareDrawData(draw_data, command_buffer);
}
extern "C" void ImGui_ImplSDLGPU3_RenderDrawData__ed2e5ca6ef1b8528(ImDrawData* draw_data, SDL_GPUCommandBuffer* command_buffer, SDL_GPURenderPass* render_pass, SDL_GPUGraphicsPipeline* pipeline) {
	ImGui_ImplSDLGPU3_RenderDrawData(draw_data, command_buffer, render_pass, pipeline);
}
extern "C" void ImGui_ImplSDLGPU3_CreateDeviceObjects__cf36dd3e42e64808() {
	ImGui_ImplSDLGPU3_CreateDeviceObjects();
}
extern "C" void ImGui_ImplSDLGPU3_DestroyDeviceObjects__98dcec2c614f2c1d() {
	ImGui_ImplSDLGPU3_DestroyDeviceObjects();
}
extern "C" void ImGui_ImplSDLGPU3_UpdateTexture__b3f7221cb5fb8d7(ImTextureData* tex) {
	ImGui_ImplSDLGPU3_UpdateTexture(tex);
}
#pragma clang diagnostic pop