// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.
const imgui = @import("../imgui.h/imgui.h.zig"); // NOTE: Patched

fn refAllDecls(comptime T: type) void {
    inline for (comptime @import("std").meta.declarations(T)) |decl| {
        _ = &@field(T, decl.name);
    }
}

pub const ImGui_ImplSDLGPU3_InitInfo = extern struct {
    Device: [*c]?*anyopaque, // NOTE: Patched
    ColorTargetFormat: i32,
    MSAASamples: i32,
    SwapchainComposition: i32,
    PresentMode: i32,
    // NOTE: Patched
};

pub const ImGui_ImplSDLGPU3_Init = ImGui_ImplSDLGPU3_Init__600d26a5acf96a01;
extern fn ImGui_ImplSDLGPU3_Init__600d26a5acf96a01(info: [*c]ImGui_ImplSDLGPU3_InitInfo) callconv(.c) bool;

pub const ImGui_ImplSDLGPU3_Shutdown = ImGui_ImplSDLGPU3_Shutdown__13b42b5729a15b3;
extern fn ImGui_ImplSDLGPU3_Shutdown__13b42b5729a15b3() callconv(.c) void;

pub const ImGui_ImplSDLGPU3_NewFrame = ImGui_ImplSDLGPU3_NewFrame__65431eefe517df84;
extern fn ImGui_ImplSDLGPU3_NewFrame__65431eefe517df84() callconv(.c) void;

pub const ImGui_ImplSDLGPU3_PrepareDrawData = ImGui_ImplSDLGPU3_PrepareDrawData__93ec289e13d03601;
// NOTE: Patched
extern fn ImGui_ImplSDLGPU3_PrepareDrawData__93ec289e13d03601(draw_data: [*c]imgui.ImDrawData, command_buffer: [*c]?*anyopaque) callconv(.c) void;

pub const ImGui_ImplSDLGPU3_RenderDrawData = ImGui_ImplSDLGPU3_RenderDrawData__ed2e5ca6ef1b8528;
// NOTE: Patched
extern fn ImGui_ImplSDLGPU3_RenderDrawData__ed2e5ca6ef1b8528(draw_data: [*c]imgui.ImDrawData, command_buffer: [*c]?*anyopaque, render_pass: [*c]?*anyopaque, pipeline: [*c]?*anyopaque) callconv(.c) void;

pub const ImGui_ImplSDLGPU3_CreateDeviceObjects = ImGui_ImplSDLGPU3_CreateDeviceObjects__cf36dd3e42e64808;
extern fn ImGui_ImplSDLGPU3_CreateDeviceObjects__cf36dd3e42e64808() callconv(.c) void;

pub const ImGui_ImplSDLGPU3_DestroyDeviceObjects = ImGui_ImplSDLGPU3_DestroyDeviceObjects__98dcec2c614f2c1d;
extern fn ImGui_ImplSDLGPU3_DestroyDeviceObjects__98dcec2c614f2c1d() callconv(.c) void;

pub const ImGui_ImplSDLGPU3_UpdateTexture = ImGui_ImplSDLGPU3_UpdateTexture__b3f7221cb5fb8d7;
extern fn ImGui_ImplSDLGPU3_UpdateTexture__b3f7221cb5fb8d7(tex: [*c]imgui.ImTextureData) callconv(.c) void;

pub const ImGui_ImplSDLGPU3_RenderState = extern struct {
    Device: [*c]i32,
    SamplerDefault: [*c]i32,
    SamplerCurrent: [*c]i32,
    // NOTE: Patched
};

comptime {
    refAllDecls(@This());
}
