// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

fn refAllDecls(comptime T: type) void {
    inline for (comptime @import("std").meta.declarations(T)) |decl| {
        _ = &@field(T, decl.name);
    }
}

pub const a1 = a1__6de793de28d24072;
extern fn a1__6de793de28d24072() callconv(.c) void;

comptime {
    refAllDecls(@This());
}
