// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

#include <stdarg.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wformat-security"

#include "a1.hpp"

extern "C" void a1__6de793de28d24072() {
	a1();
}

#pragma clang diagnostic pop
