// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

fn refAllDecls(comptime T: type) void {
    inline for (comptime @import("std").meta.declarations(T)) |decl| {
        _ = &@field(T, decl.name);
    }
}

pub const c1 = c1__bacf26633b521cb;
extern fn c1__bacf26633b521cb() callconv(.c) void;

comptime {
    refAllDecls(@This());
}
