// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

#include <stdarg.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wformat-security"

#include "c1.hpp"

extern "C" void c1__bacf26633b521cb() {
	c1();
}

#pragma clang diagnostic pop
