// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

fn refAllDecls(comptime T: type) void {
    inline for (comptime @import("std").meta.declarations(T)) |decl| {
        _ = &@field(T, decl.name);
    }
}

pub const b2 = b2__39019e2fe3c8859;
extern fn b2__39019e2fe3c8859() callconv(.c) void;

comptime {
    refAllDecls(@This());
}
