// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

#include <stdarg.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wformat-security"

#include "b2.hpp"

extern "C" void b2__39019e2fe3c8859() {
	b2();
}

#pragma clang diagnostic pop
