// -- Imports -- //

const std = @import("std");
const tracy = @import("util/tracy.zig");
const IR = @import("ir.zig").IR;

// -- Constants -- //

const WRITER_BUFFER_SIZE = 32_768;

const log = std.log.scoped(.writers);

// -- Writers -- //

/// Context to be ingested and modified by each instruction write loop.
pub const Context = struct {
    fwd_decls: std.StringHashMap(usize),
    overload_map: std.StringHashMap(usize),
    ns_stack: std.array_list.Managed([]const u8),
    member_stack: std.array_list.Managed(*std.array_list.Managed(usize)),
    parent_stack: std.array_list.Managed(Parent),
    unwind_to_parent: bool = false,

    pub const Parent = struct {
        instr_idx: usize,
        /// `writer.end` where the writing started.
        writer_start: usize,
        inner: union(enum) {
            function,
            /// The amount of unnamed fields.
            @"struct": usize,
            @"enum",
            @"union",
            namespace,
            /// The size of the field in bits.
            bitfield: usize,
            // TODO: This is for typedefs and values with members; the members should be filtered
            // TODO: out beforehand.
            ignore_members,
            root,
        },
    };
};

pub const IRWriter = struct {
    formatFilename: FormatFilename,
    initContext: ?InitContext = null,
    writeInstruction: WriteInstruction,
    writeFilePrefix: ?WriteFilePrefix = null,
    writeFileSuffix: ?WriteFileSuffix = null,
    postProcessFile: ?PostProcessFile = null,
    checkFile: ?CheckFile = null,

    const FormatFilename = *const fn (std.mem.Allocator, []const u8) std.mem.Allocator.Error![:0]const u8;
    const InitContext = *const fn (std.mem.Allocator, *Context) anyerror!void;
    const WriteFilePrefix = *const fn (*const IR, *std.Io.Writer) anyerror!void;
    const WriteInstruction = *const fn (*const IR, usize, *Context, *std.Io.Writer) WriteInstructionError!void;
    const WriteFileSuffix = *const fn (*const IR, *std.Io.Writer) anyerror!void;
    const PostProcessFile = *const fn (std.mem.Allocator, []const u8) anyerror!void;
    const CheckFile = *const fn (std.mem.Allocator, [:0]const u8, anytype) anyerror!bool;

    pub const WriteInstructionError = error{
        Revert,
    } || std.mem.Allocator.Error || std.Io.Writer.Error;
};

// -- Implementations -- //

const cpp = @import("writers/cpp.zig");
pub const CppWrapper: IRWriter = .{
    .formatFilename = cpp.formatFilename,
    .initContext = cpp.initContext,
    .writeInstruction = cpp.writeInstruction,
    .writeFilePrefix = cpp.writeFilePrefix,
    .writeFileSuffix = cpp.writeFileSuffix,
    .checkFile = cpp.checkFile,
};

// pub const ZigWrapper: IRWriter = .{
//     .formatFilename = @import("writers/zig.zig").formatFilename,
//     .formatFile = @import("writers/zig.zig").formatFile,
//     .postProcessFile = @import("writers/zig.zig").postProcessFile,
//     .checkFile = @import("writers/zig.zig").checkFile,
// };

// -- Un-translate-able Types -- //

pub const untranslateable_types: std.StaticStringMap(void) = .initComptime(.{
    .{"va_list"},
});

// -- Helpers -- //

pub const PREAMBLE = "// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.";

pub fn writeToFile(
    allocator: std.mem.Allocator,
    ir: *const IR,
    ir_writer: IRWriter,
    filename: []const u8,
) !void {
    var fz = tracy.FnZone.init(@src(), "writers.writeToFile");
    defer fz.end();

    const formatted_filename = try ir_writer.formatFilename(allocator, filename);

    var file = try std.fs.cwd().createFile(formatted_filename, .{});
    var buffer: [WRITER_BUFFER_SIZE]u8 = undefined;
    @memset(&buffer, 0);
    var writer = file.writer(&buffer);

    if (ir_writer.writeFilePrefix) |wfp| try wfp(ir, &writer.interface);

    var ctx: Context = .{
        .fwd_decls = .init(allocator),
        .overload_map = .init(allocator),
        .ns_stack = .init(allocator),
        .member_stack = .init(allocator),
        .parent_stack = .init(allocator),
    };
    if (ir_writer.initContext) |ic| try ic(allocator, &ctx);

    var i: usize = 0;
    while (i < ir.instrs.items.len) : (i += 1) {
        ir_writer.writeInstruction(ir, i, &ctx, &writer.interface) catch |e| switch (e) {
            error.Revert => {
                // Add reason for the reversion.
                log.err("Reverting '{s}' write.", .{ir.instrs.items[ctx.parent_stack.getLast().instr_idx].name});
                ctx.unwind_to_parent = true;
            },
            else => return e,
        };
    }

    if (ir_writer.writeFileSuffix) |wfs| try wfs(ir, &writer.interface);

    try writer.interface.flush();
    file.close();

    if (ir_writer.postProcessFile) |ppf| try ppf(allocator, formatted_filename);
}

pub fn checkFile(
    allocator: std.mem.Allocator,
    ir_writer: IRWriter,
    filename: []const u8,
    args: anytype,
) !void {
    var fz = tracy.FnZone.init(@src(), "writers.checkFile");
    defer fz.end();

    if (ir_writer.checkFile == null) {
        std.log.err("Nothing to check the file with for IRWriter!", .{});
        return;
    }

    const formatted_filename = try ir_writer.formatFilename(allocator, filename);

    const good = try ir_writer.checkFile.?(
        allocator,
        formatted_filename,
        args,
    );

    if (!good) {
        std.log.err("'{s}' failed checks!", .{formatted_filename});
    }
}
