// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

fn refAllDecls(comptime T: type) void {
    inline for (comptime @import("std").meta.declarations(T)) |decl| {
        _ = &@field(T, decl.name);
    }
}

pub const c2 = c2__952deaef11a87052;
extern fn c2__952deaef11a87052() callconv(.c) void;

comptime {
    refAllDecls(@This());
}
