// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

#include <stdarg.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wformat-security"

#include "c2.hpp"

extern "C" void c2__952deaef11a87052() {
	c2();
}

#pragma clang diagnostic pop
