// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

#include <stdarg.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wformat-security"

#include "a3.hpp"

extern "C" void a3__8dea8bbc5f09cbb8() {
	a3();
}

#pragma clang diagnostic pop
