// This file was auto-generated by github:nukkeldev/zpp; I wouldn't recommend editing it.

fn refAllDecls(comptime T: type) void {
    inline for (comptime @import("std").meta.declarations(T)) |decl| {
        _ = &@field(T, decl.name);
    }
}

pub const a3 = a3__8dea8bbc5f09cbb8;
extern fn a3__8dea8bbc5f09cbb8() callconv(.c) void;

comptime {
    refAllDecls(@This());
}
